apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: {{ .Values.namespace }}
  labels:
    app: app
  annotations:
    deployment.kubernetes.io/revision: "2"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-helloworld: secret/data/secret/secret
    vault.hashicorp.com/agent-inject-template-helloworld: |
      {{- with secret "secret/data/secret/secret" -}}
      {{ .Data.data.password }}
      {{- end }}
    vault.hashicorp.com/role: app
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-helloworld: secret/data/secret/secret
        vault.hashicorp.com/agent-inject-template-helloworld: |
          {{- with secret "secret/data/secret/secret" -}}
          {{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/role: app
    spec:
      containers:
      - name: app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
          - containerPort: {{ .Values.service.port }}
            name: "http-server"
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        env:
          - name: DATABASE_HOSTS
            value: {{ .Values.env.databaseHost }}
          - name: DATABASE_URI
            value: {{ .Values.env.databaseUri }}
---