apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
  labels:
    app: app
  annotations:
    deployment.kubernetes.io/revision: "2"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-secret-helloworld: secret/data/secret/secret
    vault.hashicorp.com/agent-inject-template-helloworld: |
      {{- with secret "secret/data/secret/secret" -}}
      {{ .Data.data.password }}
      {{- end }}
    vault.hashicorp.com/role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-helloworld: secret/data/secret/secret
        vault.hashicorp.com/agent-inject-template-helloworld: |
          {{- with secret "secret/data/secret/secret" -}}
          {{ .Data.data.password }}
          {{- end }}
        vault.hashicorp.com/role: app
    spec:
      containers:
      - name: app
        image: cr.yandex/crp0irehbbj1n4pd0tf1/flask-app:v7
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
            name: "http-server"
        resources:
          requests:
            memory: 250Mi
            cpu: 300m
          limits:
            memory: 1Gi
            cpu: 600m
        env:
          - name: DATABASE_HOSTS
            value: postgres-service
          - name: DATABASE_URI
            value: postgresql://username:password@postgres-service:5432/hw_db?sslmode=disable